import { Dimensions, StyleSheet } from 'react-native';
import Constants from '../../Variables/colors.variables';

const Styles = StyleSheet.create({
  container: {
    backgroundColor: Constants.appBackgroundColor,
    alignItems: 'flex-start',
    flex: 1,
  },
  buttonSection: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 12,
    marginVertical: 16,
  },
  active: {
    backgroundColor: Constants.primaryColor,
    width: Dimensions.get('window').width / 3 - 12,
    borderRadius: 7,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    marginHorizontal: 4,
  },
  inactive: {
    backgroundColor: Constants.appBackgroundColor,
    width: Dimensions.get('window').width / 3 - 12,
    borderRadius: 7,
    paddingVertical: 12,
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 4,
  },
  activeButtonText: {
    fontSize: 15,
    fontFamily: 'Poppins-Medium',
    color: 'white',
    textAlign: 'center',
  },
  inactiveButtonText: {
    fontSize: 15,
    fontFamily: 'Poppins-Medium',
    color: '#646466',
    textAlign: 'center',
  },
  generalSection: {
    marginHorizontal: 16,
    marginVertical: 8,
  },
  errorSection: {
    paddingHorizontal: 16,
    marginVertical: 8,
    flex: 1,
    width: Dimensions.get('window').width,
    justifyContent: 'center',
    alignItems: 'center',
  },
  codSection: {
    marginHorizontal: 16,
    marginVertical: 8,
  },
  DownArrow: {
    height: 25,
    width: 25,
  },
  UpArrow: {
    height: 25,
    width: 25,
  },
  DownArrowView: {
    paddingLeft: 60,
    paddingTop: 5,
  },
  codCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    width: Dimensions.get('window').width - 32,
    flexDirection: 'row',
    padding: 16,
    marginVertical: 8,
  },
  codCardDown: {
    backgroundColor: 'white',
    borderRadius: 12,
    width: Dimensions.get('window').width - 32,
    flexDirection: 'row',
    padding: 16,
    marginBottom: 20,
  },
  codLeftSections: {
    flexDirection: 'row',
    zIndex: 1,
  },
  codLeftSection: {
    width: 34,
    height: 34,
    borderRadius: 20,
    backgroundColor: '#CEEFFB',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  orderID: {
    fontSize: 12,
    fontFamily: 'Poppins-Regular',
    color: Constants.primaryColor,
    marginLeft: 4,
  },
  errorMessage: {
    fontSize: 15,
    fontFamily: 'Poppins-Medium',
    color: '#222224',
    textAlign: 'center',
  },
  codName: {
    fontSize: 15,
    fontFamily: 'Poppins-Medium',
    color: '#222224',
    textAlign: 'center',
  },
  codAmount: {
    color: '#21B535',
    fontSize: 13,
    fontFamily: 'Poppins-Medium',
  },
  generalCard1: {
    backgroundColor: '#FDF5DE',
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
    textAlign: 'center',
    minHeight: 90,
    width: Dimensions.get('window').width - 32,
    marginVertical: 8,
  },
  generalCard2: {
    backgroundColor: '#FFE4E4',
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
    textAlign: 'center',
    minHeight: 90,
    width: Dimensions.get('window').width - 32,
    marginVertical: 8,
  },
  generalCard3: {
    backgroundColor: '#E5F8E2',
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
    textAlign: 'center',
    minHeight: 90,
    width: Dimensions.get('window').width - 32,
    marginVertical: 8,
  },
  generalHeading: {
    fontSize: 15,
    fontFamily: 'Poppins-Medium',
    color: '#222224',
    textAlign: 'center',
    marginBottom: 6,
  },
  generalSubHeading: {
    fontSize: 20,
    fontFamily: 'Poppins-Medium',
    color: '#222224',
    textAlign: 'center',
    marginBottom: 6,
  },

  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: '#F194FF',
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  monthSlotStyles: {
    alignItems: 'center',
    justifyContent: 'center',
    width: Dimensions.get('window').width - 30,
    height: 35,
    backgroundColor: '#rgb(95,165,113)',
    borderRadius: 5,
  },
  datstyle: {
    color: '#000',
    fontSize: 16,
    fontWeight: '500',
  },
  datstyles: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '500',
  },
  vvstyle: {
    // paddingTop: 20,
    marginVertical: 10,
  },
});

export default Styles;
