import { Dimensions, StyleSheet } from 'react-native';
import Constants from '../../../Variables/colors.variables';

const Styles = StyleSheet.create({
  heading: {
    fontFamily: 'Poppins-SemiBold',
    color: Constants.headingColor,
    fontSize: 18,
    marginBottom: 12,
  },
  actionsSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginBottom: 20,
  },
  actionCardAddOrder: {
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: Constants.lightColor,
    backgroundColor: '#BAF5BC',
    height: Dimensions.get('window').width / 2 - 50,
    padding: 12,
    width: Dimensions.get('window').width / 2 - 50,
  },
  actionCardQuickRecharge: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 12,
    alignSelf: 'center',
    borderColor: Constants.lightColor,
    backgroundColor: '#CECDFF',
    height: Dimensions.get('window').width / 2 - 50,
    width: Dimensions.get('window').width / 2 - 50,
  },
  actionCardQuickRecharges: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 12,
    borderColor: Constants.lightColor,
    backgroundColor: '#CECDFF',
    height: Dimensions.get('window').width / 2 - 50,
    width: Dimensions.get('window').width / 2 - 50,
  },
  possesionStyles: {
    paddingLeft: 15,
  },
  actionCardCalculator: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderColor: Constants.lightColor,
    backgroundColor: '#B6EEF2',
    height: Dimensions.get('window').width / 2 - 50,
    padding: 12,
    width: Dimensions.get('window').width / 2 - 50,
  },
  actionCardScanner: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderColor: Constants.lightColor,
    backgroundColor: '#B8D5FF',
    height: Dimensions.get('window').width / 2 - 50,
    padding: 12,
    width: Dimensions.get('window').width / 2 - 50,
  },
  noCard: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'white',
    height: Dimensions.get('window').width / 2 - 50,
    padding: 12,
    width: Dimensions.get('window').width / 2 - 50,
  },
  actionCardCustomer: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderColor: Constants.lightColor,
    backgroundColor: '#FFFFE0',
    height: Dimensions.get('window').width / 2 - 50,
    padding: 12,
    width: Dimensions.get('window').width / 2 - 50,
  },
  actionText: {
    color: Constants.headingColor,
    marginTop: 11,
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    textAlign: 'center',
  },
  actionImage: {
    width: 55,
    height: 55,
  },
  actionImagess: {
    width: 25,
    height: 25,
  },
  rechargeInputStyles: {
    color: '#000',
    borderWidth: 0.5,
    borderRadius: 5,
    paddingLeft: 10,
    width: (Dimensions.get('window').width * 2) / 3.5,
  },
  rechargeBtnStyles: {
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Constants.primaryColor,
    height: 50,
    width: Dimensions.get('window').width / 3,
  },
  btnContainer: {
    paddingVertical: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  rechargeText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: 'bold',
  },
});

export default Styles;
